# Generated by Django 5.1.4 on 2026-06-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Extra Mileage Logistics', max_length=120)),
                ('tagline', models.CharField(default='Premium Japanese Used Cars Export', max_length=200)),
                ('site_description', models.TextField(default='Quality vehicles direct from Japan, shipped worldwide.')),
                ('contact_email', models.EmailField(default='info@extramileage.com', max_length=254)),
                ('contact_phone', models.CharField(default='+81 (0)-80-7050-3366', max_length=40)),
                ('whatsapp_number', models.CharField(blank=True, default='+81-80-7050-3366', max_length=40)),
                ('company_address', models.CharField(default='1-2-3 Shibuya, Shibuya City, Tokyo 150-0002, Japan', max_length=200)),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/Extramileage')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com/Extramileage')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/Extramileage')),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com/company/Extramileage')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com/@Extramileage')),
                ('tiktok', models.URLField(blank=True, default='https://tiktok.com/@Extramileage')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('button_text', models.CharField(default='Browse Cars', max_length=60)),
                ('link', models.CharField(default='/cars/', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('avatar_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
