# Generated by Django 5.1.4 on 2026-06-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon name, e.g. car', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(blank=True, help_text='ISO alpha-2, e.g. jp', max_length=2)),
                ('flag_emoji', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=30, unique=True)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fob_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cif_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage', models.PositiveIntegerField(default=0, help_text='km')),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('certified', 'Certified Pre-Owned')], default='used', max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT'), ('AMT', 'AMT')], default='Automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric'), ('Plug-in Hybrid', 'Plug-in Hybrid')], default='Petrol', max_length=20)),
                ('drivetrain', models.CharField(choices=[('2WD', '2WD'), ('4WD', '4WD'), ('AWD', 'AWD'), ('FWD', 'FWD'), ('RWD', 'RWD')], default='2WD', max_length=10)),
                ('steering', models.CharField(choices=[('Right', 'Right Hand'), ('Left', 'Left Hand')], default='Right', max_length=10)),
                ('engine_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=40)),
                ('doors', models.PositiveSmallIntegerField(default=4)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('location', models.CharField(default='Japan', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.category')),
                ('origin_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='catalog.country')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.car')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
            },
        ),
    ]
